### ISSUE TITLE
2.2.2 breaking change: 'modifier' keyword is now overridden by local state

### ISSUE THREAD

**Issue by davidtaylorhq** [emberjs/babel-plugin-ember-template-compilation#39]
This worked under 2.2.1:
```gjs
import { modifier } from "ember-modifier";

const addClass = modifier((el) => {
  el.classList.add("foo");
});

const shouldAddClass = true;

<template>
  <div {{(if shouldAddClass (modifier addClass))}}>
  </div>
</template>
```

`modifier` in the template would refer to the built-in modifier helper, **not** the `modifier` function in the local scope.

Under 2.2.2, the template now takes `modifier` from the local scope, which (understandably) leads to some very strange errors.

We can work around the issue by changing the name of the import like

```
import { modifier as renamedModifier } from "ember-modifier";
```
so that it doesn't clash with the builtin. 

Clearly the old behaviour was quite 'magic'... so changing the behaviour here in a major version seems reasonable. Perhaps the modifier helper should always be explicitly imported, rather than being a built-in? But having this behaviour change as part of a patch version bump is not ideal.

**Comment by ef4** [comment]
The change was intentional. Javascript locals must win over ember keywords or otherwise it will be impossible for ember to ever introduce a new keyword, since we could never know if you had already used that name in your javascript somewhere.  It was always supposed to work this way, it was a bug that it didn't. 

I was hoping this isn't already a widely-depended-upon bug, and that getting the fix to everywhere as immediately as possible via a patch would do the most to prevent problems down the road. I'm inclined to wait a bit to gauge the impact before we do something like revert this and switch to a major. The problem with a major in babel-plugin-ember-template-compilation is that it's not actually a dependency that classic apps can directly control, so if we go that route people are going to keep having the buggy version for a long time, and write even more code that depends on the bug, making the eventual upgrade harder.

**Comment by NullVoxPopuli** [comment]
@davidtaylorhq i ran in to this myself.

It's something that came up during the FCCT RFC, and kinda silly this behavior was forgotten till now 😅
I'm glad it's fixed tho, because the Magic behavior was a bit hard to explain consistently.

That said, i'm more than happy to update any addon that now needs fixed

**Comment by davidtaylorhq** [comment]
Ok I can see the logic there, thanks for explaining! We have quite a few spots to fix up in Discourse (and potentially Discourse plugins/themes), but it shouldn't be too bad.

I'm wondering if there's any sensible way we could lint for this? The new behaviour is still 'magic', and eslint/ember-template-lint give us no warning that we accidentally broke a built-in keyword in the template. 🤔 

Using the `modifier` helper is relatively rare, so I would be quite happy if it had to be imported, rather than being a keyword. (but of course, that would be another breaking change).
